from datetime import date, timedelta
from decimal import Decimal

from django.core.management.base import BaseCommand

from apps.invoices.models import Invoice, InvoiceItem
from apps.users.models import User


class Command(BaseCommand):
    help = "Create demo users and sample invoices for local manual testing."

    def handle(self, *args, **options):
        admin, _ = User.objects.get_or_create(
            username="admin_demo",
            defaults={
                "email": "admin@demo.local",
                "role": User.Role.ADMIN,
                "company_name": "Demo Inc",
                "is_staff": True,
                "is_superuser": True,
            },
        )
        admin.set_password("admin12345")
        admin.save()

        manager, _ = User.objects.get_or_create(
            username="manager_demo",
            defaults={
                "email": "manager@demo.local",
                "role": User.Role.MANAGER,
                "company_name": "Demo Inc",
            },
        )
        manager.set_password("manager12345")
        manager.save()

        invoice, _ = Invoice.objects.get_or_create(
            owner=manager,
            number="INV-DEMO-001",
            defaults={
                "customer_name": "Acme Corp",
                "customer_email": "billing@acme.test",
                "issue_date": date.today(),
                "due_date": date.today() + timedelta(days=7),
                "status": Invoice.Status.SENT,
                "notes": "Demo invoice generated by seed command",
            },
        )

        if not invoice.items.exists():
            InvoiceItem.objects.create(
                invoice=invoice,
                description="Backend development",
                quantity=Decimal("8.00"),
                unit_price=Decimal("50.00"),
            )
            InvoiceItem.objects.create(
                invoice=invoice,
                description="Frontend integration",
                quantity=Decimal("4.00"),
                unit_price=Decimal("45.00"),
            )

        self.stdout.write(self.style.SUCCESS("Demo data seeded successfully."))
        self.stdout.write("Users:")
        self.stdout.write("  admin_demo / admin12345")
        self.stdout.write("  manager_demo / manager12345")

